[project]
name = "issueflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.5.5",
    "httpx>=0.28.1",
    "polars[rtcompat]>=1.44.2",
    "prefect>=3.8.7",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv.workspace]
members = ["code/*"]
exclude = ["code/issueflow"]
